project:
  type: website
  output-dir: docs 

website:
  title: "portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: person
        href: https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:8122136b-42b8-4381-b74e-f70cab8aa325?x_api_client_id=edge_extension_viewer&x_api_client_location=share&locale=en-US&theme=light&page_theme=light&show_copied_toast=true
      - icon: box
        href: https://acrobat.adobe.com/id/urn:aaid:sc:VA6C2:e42e65fc-d6fc-4f86-b33e-743737610f6c?x_api_client_id=edge_extension_viewer&x_api_client_location=share&locale=en-US&theme=light&page_theme=light&show_copied_toast=true
        
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



